In [1]:
import numpy as np
#import sys

#sys.path.append(r"../fermifab") 
#from fermistate import *
#from fermiop import *
#from rdm import *

from fermifab.fermistate import *
from fermifab.fermiop import *
from fermifab.rdm import *
# autoreload during development; see https://ipython.org/ipython-doc/3/config/extensions/autoreload.html

%load_ext autoreload
%autoreload 2

In [2]:
# construct fermionic quantum state
# number of "orbitals" (slots)
orbs = 6
# number of particles (occupied orbitals)
N = 4
psi = FermiState(orbs, N)
psi.data[0] = 1. /np.sqrt(2)
psi.data[1] = 1.j/np.sqrt(2)
psi

Fermi State (orbs == 6, N == 4)

Vector representation w.r.t. ordered Slater basis:

array([0.70710678+0.j        , 0.        +0.70710678j,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        ])

In [3]:
# create another fermionic state and add them up
phi = FermiState(orbs, N)
phi.data[0] = 1. /np.sqrt(2)
phi.data[2] = 1. /np.sqrt(2)
chi = psi + phi
chi

Fermi State (orbs == 6, N == 4)

Vector representation w.r.t. ordered Slater basis:

array([1.41421356+0.j        , 0.        +0.70710678j,
       0.70710678+0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        ])

In [4]:
# compute density matrix of psi
rho = psi * psi.T
rho.data[:2,:2]

array([[0.5+0.j , 0. -0.5j],
       [0. +0.5j, 0.5+0.j ]])

In [5]:
# compute two-body reduced density matrix
G = rdm(psi, 2) # now this returns a FermiOp object
G.data[:7,:4] # same results as in the FermiFab User's Guide

array([[1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 1. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0.5+0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
       [0. +0.j , 0. +0.j , 0. +0.j , 0. +0.5j]])

In [6]:
# Expected value of G under psi:
psi.T * G * psi

(0.9999999999999997+0j)